language: cpp
compiler: gcc
sudo: require
dist: xenial

install:
  - sudo apt-get -y install g++ inkscape libgegl-dev libcairo2-dev libcairo2-dev libcups2-dev libfontconfig-dev libfreetype6-dev libftgl-dev libglu1-mesa-dev libgraphicsmagick++1-dev libimlib2-dev libpng12-dev libreadline-dev libssl-dev libx11-dev libxext-dev libxft-dev libxi-dev libxrandr-dev mesa-common-dev pkg-config xutils-dev zlib1g-dev
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc # Needed for std=c++11?
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++ # Needed for std=c++11?

script:
  - export CXXFLAGS='-std=c++11'
  # Harfbuzz
  - wget https://github.com/behdad/harfbuzz/releases/download/2.2.0/harfbuzz-2.2.0.tar.bz2
  - tar xf harfbuzz-2.2.0.tar.bz2
  - cd harfbuzz-2.2.0
  - ./configure --prefix=/usr --disable-dependency-tracking --disable-static --with-glib=no --with-gobject=no --with-cairo=no --with-fontconfig=no --with-icu=no --with-directwrite=no --with-freetype=yes
  - make -j$(nproc)
  - sudo make install
  - pkg-config --cflags harfbuzz
  - cd ..
  # laxkit
  - git clone http://github.com/Laidout/laxkit.git laxkit
  - cd laxkit
  - ./configure --disable-sqlite
  - make -j$(nproc)
  - cd ..
  # Laidout
  - mkdir -p appdir
  - ./configure --prefix=`pwd`/appdir --laxkit=`pwd`/laxkit/lax --nogl --disable-sqlite --force --gegl-version=gegl-0.3
  - make -j$(nproc)
  # TODO: Making the icons requires Inkscape(!); FIXME, see https://github.com/Laidout/laidout
  - sudo make install DESTDIR=$(readlink -f appdir) ; find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Laidout*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
