language: cpp
compiler: gcc
sudo: require
dist: xenial

install:
  - sudo apt-get -y install g++ inkscape libgegl-dev libcairo2-dev libcairo2-dev libcups2-dev libfontconfig-dev libfreetype6-dev libftgl-dev libglu1-mesa-dev libgraphicsmagick++1-dev libimlib2-dev libpng12-dev libreadline-dev libssl-dev libx11-dev libxext-dev libxft-dev libxi-dev libxrandr-dev mesa-common-dev pkg-config xutils-dev zlib1g-dev
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc # Needed for std=c++11?
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++ # Needed for std=c++11?

script:
  - export CXXFLAGS='-std=c++11'
  # Harfbuzz
  - wget https://github.com/behdad/harfbuzz/releases/download/2.2.0/harfbuzz-2.2.0.tar.bz2
  - tar xf harfbuzz-2.2.0.tar.bz2
  - cd harfbuzz-2.2.0
  - ./configure --prefix=/usr --disable-dependency-tracking --disable-static --with-glib=no --with-gobject=no --with-cairo=no --with-fontconfig=no --with-icu=no --with-directwrite=no --with-freetype=yes
  - make -j$(nproc)
  - sudo make install
  - pkg-config --cflags harfbuzz
  - cd ..
  # laxkit
  - git clone http://github.com/Laidout/laxkit.git laxkit
  - cd laxkit
  - ./configure --disable-sqlite --relocatable
  - make -j$(nproc)
  - cd ..
  # Laidout 
  - mkdir -p appdir
  - cp AppRun appdir/ ; chmod +x appdir/AppRun
  - ./configure --prefix=`pwd`/appdir/usr --relocatable --laxkit=`pwd`/laxkit/lax --nogl --disable-sqlite --force --gegl-version=gegl-0.3
  - make -j$(nproc)
  # TODO: Making the icons requires Inkscape(!); FIXME, see https://github.com/Laidout/laidout
  - git clone https://github.com/Laidout/laidout-icons
  - cp laidout-icons/target-24/* src/icons
  - make install
  - mkdir -p appdir/ usr/lib/x86_64-linux-gnu/ ; cp -r /usr/lib/x86_64-linux-gnu/gegl-* appdir/usr/lib/x86_64-linux-gnu/
  - mkdir -p appdir/usr/share/applications/ ; cp deb/laidout.desktop appdir/usr/share/applications/ # FIXME: make install should do this
  - mkdir -p appdir/usr/share/icons/hicolor/scalable/apps/ ; cp src/icons/laidout.svg appdir/usr/share/icons/hicolor/scalable/apps/ # FIXME: make install should do this
  - find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - | 
    ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage \
    -executable=$(readlink -f appdir/usr/share/laidout/*/plugins/geglnodes.so) \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/exr-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/ff-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/ff-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/gegl-common-cxx.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/gegl-common-gpl3.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/gegl-common.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/gegl-core.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/gegl-generated.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/gif-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/jpg-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/jpg-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/lcms-from-profile.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/matting-levin.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/npd.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/npy-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/path.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/pdf-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/pixbuf.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/png-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/png-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/ppm-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/ppm-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/raw-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/rgbe-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/rgbe-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/save-pixbuf.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/sdl-display.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/seamless-clone-compose.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/seamless-clone.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/svg-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/text.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/tiff-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/tiff-save.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/transformops.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/vector-fill.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/vector-stroke.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/webp-load.so \
    -executable=appdir/usr/lib/x86_64-linux-gnu/gegl-0.4/webp-save.so

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Laidout*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
